### ISSUE TITLE
`required` after `move` not working

### ISSUE THREAD

**Issue by taoalpha** [adamjeffries/typedef.js#6]
Following is not working:
```
oh.object({
  id: oh.move("pid").required
});
```
has to be:
```
oh.object({
  id: oh.required.move("pid")
});
```

**Comment by adamjeffries** [comment]
Fixed and Deployed: https://github.com/adamjeffries/overhaul/commit/e7588294efb9a357beabf339dbebd0f04e6c126b

**Comment by tao-si** [comment]
new issues brought by this fix:

expected behaviors:
```
oh.object({
  id: oh.move("pid").required
}).value({
 pid: "aaa"
});
// should work fine
```
current behaviors: throw error for `pid` required

but i got the reason, since it only checks keys list inside... and no `pid` list as key

**Comment by taoalpha** [comment]
new issues brought by this fix:

expected behaviors:
```
oh.object({
  id: oh.move("pid").required
}).value({
 pid: "aaa"
});
// should work fine
```
current behaviors: throw error for `pid` required

but i got the reason, since it only checks keys list inside... and no `pid` list as key
